import { Layout } from '@/components/layout/Layout';

export default function Terms() {
    return (
        <Layout>
            <div className="container mx-auto px-4 py-16 max-w-4xl">
                <article className="prose prose-invert mx-auto">
                    <h1>Terms of Service</h1>

                    <p className="text-muted-foreground">
                        Last Updated: January 16, 2026
                    </p>

                    <h2>Agreement to Terms</h2>
                    <p>
                        By accessing and using Nine Hub Tools ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
                    </p>

                    <h2>Description of Service</h2>
                    <p>
                        Nine Hub Tools provides free, web-based design tools for developers and designers. Our tools include:
                    </p>
                    <ul>
                        <li>Glassmorphism Generator</li>
                        <li>Gradient Text Generator</li>
                        <li>Box Shadow Generator</li>
                        <li>Color Palette Generator</li>
                        <li>CSS Grid Generator</li>
                        <li>Blob SVG Generator</li>
                        <li>Contrast Checker</li>
                        <li>Meta Tag Generator</li>
                        <li>AI Prompt Helper</li>
                    </ul>

                    <h2>Free Service</h2>
                    <p>
                        Nine Hub Tools is currently provided free of charge. We reserve the right to introduce paid features or subscription tiers in the future, but existing free features will remain available.
                    </p>

                    <h2>User Responsibilities</h2>
                    <p>You agree to:</p>
                    <ul>
                        <li>Use the Service only for lawful purposes</li>
                        <li>Not attempt to interfere with or disrupt the Service</li>
                        <li>Not use automated tools to scrape or download content in bulk</li>
                        <li>Not reverse engineer or attempt to extract source code</li>
                        <li>Respect the intellectual property rights of others</li>
                    </ul>

                    <h2>Intellectual Property</h2>

                    <h3>Generated Code</h3>
                    <p>
                        All CSS, HTML, SVG, and other code generated by our tools is yours to use freely without restriction. You may use it in personal or commercial projects.
                    </p>

                    <h3>Service Content</h3>
                    <p>
                        The Nine Hub Tools website, design, interface, and tool implementations are protected by copyright and other intellectual property laws. You may not copy, modify, or redistribute the Service itself.
                    </p>

                    <h2>Disclaimer of Warranties</h2>
                    <p>
                        The Service is provided "as is" without warranties of any kind, either express or implied. We do not guarantee that:
                    </p>
                    <ul>
                        <li>The Service will be uninterrupted or error-free</li>
                        <li>Generated code will be free from bugs</li>
                        <li>The Service will meet your specific requirements</li>
                        <li>Any data you save will be permanently stored</li>
                    </ul>

                    <h2>Limitation of Liability</h2>
                    <p>
                        To the maximum extent permitted by law, Nine Hub Tools shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the Service.
                    </p>

                    <h2>User Content and Data</h2>
                    <p>
                        Any configurations, presets, or settings you save are stored locally in your browser. We are not responsible for loss of locally stored data. We recommend exporting important configurations.
                    </p>

                    <h2>Third-Party Services</h2>
                    <p>
                        Our Service may contain links to third-party websites or integrate with third-party services. We are not responsible for the content or practices of these third parties.
                    </p>

                    <h2>Changes to Terms</h2>
                    <p>
                        We reserve the right to modify these Terms at any time. We will notify users of significant changes by posting a notice on our website. Continued use of the Service after changes constitutes acceptance of the new Terms.
                    </p>

                    <h2>Termination</h2>
                    <p>
                        We reserve the right to terminate or suspend access to the Service without prior notice for conduct that violates these Terms or is harmful to other users, us, or third parties.
                    </p>

                    <h2>Governing Law</h2>
                    <p>
                        These Terms shall be governed by and construed in accordance with applicable international laws, without regard to conflict of law principles.
                    </p>

                    <h2>Contact Information</h2>
                    <p>
                        For questions about these Terms of Service, please contact us:
                    </p>
                    <ul>
                        <li>Email: <a href="mailto:hello@nineproo.com">hello@nineproo.com</a></li>
                        <li>Website: <a href="https://nineproo.com/contact">nineproo.com/contact</a></li>
                    </ul>

                    <h2>Acceptance</h2>
                    <p>
                        By using Nine Hub Tools, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
                    </p>
                </article>
            </div>
        </Layout>
    );
}
