export interface PageSEO {
    title: string;
    description: string;
    keywords: string[];
    canonical: string;
    ogImage?: string;
    schema?: any;
}

export const seoConfig: Record<string, PageSEO> = {
    '/': {
        title: 'Nine Hub Tools - Free Web Design Tools for Developers',
        description: 'Professional design tools for web developers. Generate glassmorphism, gradients, shadows, color palettes, and more. Free and open-source.',
        keywords: ['free web tools', 'developer tools', 'web design tools', 'css generator'],
        canonical: 'https://nineproo.com/',
        schema: [
            {
                "@context": "https://schema.org",
                "@type": "WebSite",
                "name": "NineProo",
                "alternateName": "Nine Hub Tools",
                "url": "https://nineproo.com",
                "description": "Free online web design tools for developers, designers, and creators"
            },
            {
                "@context": "https://schema.org",
                "@type": "Organization",
                "name": "NineProo",
                "url": "https://nineproo.com",
                "logo": "https://nineproo.com/logo.png",
                "sameAs": [
                    "https://x.com/nine_proo",
                    "https://www.instagram.com/nine_proo/",
                    "https://github.com"
                ],
                "contactPoint": {
                    "@type": "ContactPoint",
                    "email": "hello@nineproo.com",
                    "contactType": "Customer Service"
                }
            },
            {
                "@context": "https://schema.org",
                "@type": "FAQPage",
                "mainEntity": [
                    {
                        "@type": "Question",
                        "name": "Are these tools completely free to use?",
                        "acceptedAnswer": {
                            "@type": "Answer",
                            "text": "Yes! All current tools are 100% free to use with no restrictions. You can generate unlimited CSS effects, gradients, and designs. Premium features may be added in the future for advanced users, but all existing tools will remain free."
                        }
                    },
                    {
                        "@type": "Question",
                        "name": "Do I need to create an account?",
                        "acceptedAnswer": {
                            "@type": "Answer",
                            "text": "No account required! All tools work instantly in your browser. Simply visit any tool, customize your design, and copy the generated code. No signup, no login, no hassle."
                        }
                    },
                    {
                        "@type": "Question",
                        "name": "Can I use the generated code in commercial projects?",
                        "acceptedAnswer": {
                            "@type": "Answer",
                            "text": "Absolutely! All code generated by our tools is yours to use in any project, whether personal or commercial. No attribution required, no licensing fees."
                        }
                    },
                    {
                        "@type": "Question",
                        "name": "Which browsers are supported?",
                        "acceptedAnswer": {
                            "@type": "Answer",
                            "text": "Our tools work on all modern browsers including Chrome, Firefox, Safari, and Edge. We recommend using the latest version of your browser for the best experience."
                        }
                    },
                    {
                        "@type": "Question",
                        "name": "What code formats can I export?",
                        "acceptedAnswer": {
                            "@type": "Answer",
                            "text": "Most tools support multiple export formats including pure CSS, Tailwind CSS, and React/JSX. You can choose the format that best fits your workflow and copy it with one click."
                        }
                    },
                    {
                        "@type": "Question",
                        "name": "How do I report a bug or request a feature?",
                        "acceptedAnswer": {
                            "@type": "Answer",
                            "text": "We love feedback! Contact us at hello@nineproo.com with bug reports, feature requests, or suggestions. You can also reach out via our social media channels on X or Instagram."
                        }
                    }
                ]
            },
            {
                "@context": "https://schema.org",
                "@type": "CollectionPage",
                "name": "Free Web Design Tool Collection",
                "description": "Collection of 9 free web design generators for CSS, Tailwind, and React",
                "url": "https://nineproo.com",
                "hasPart": [
                    {
                        "@type": "SoftwareApplication",
                        "name": "Glassmorphism Generator",
                        "url": "https://nineproo.com/glass",
                        "applicationCategory": "DesignApplication",
                        "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" }
                    },
                    {
                        "@type": "SoftwareApplication",
                        "name": "Gradient Text Generator",
                        "url": "https://nineproo.com/gradient-text",
                        "applicationCategory": "DesignApplication",
                        "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" }
                    },
                    {
                        "@type": "SoftwareApplication",
                        "name": "Box Shadow Generator",
                        "url": "https://nineproo.com/shadow",
                        "applicationCategory": "DesignApplication",
                        "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" }
                    },
                    {
                        "@type": "SoftwareApplication",
                        "name": "Color Palette Generator",
                        "url": "https://nineproo.com/palette",
                        "applicationCategory": "DesignApplication",
                        "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" }
                    },
                    {
                        "@type": "SoftwareApplication",
                        "name": "CSS Grid Generator",
                        "url": "https://nineproo.com/grid",
                        "applicationCategory": "DesignApplication",
                        "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" }
                    },
                    {
                        "@type": "SoftwareApplication",
                        "name": "Blob SVG Generator",
                        "url": "https://nineproo.com/blob",
                        "applicationCategory": "DesignApplication",
                        "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" }
                    },
                    {
                        "@type": "SoftwareApplication",
                        "name": "Contrast Checker",
                        "url": "https://nineproo.com/contrast",
                        "applicationCategory": "DesignApplication",
                        "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" }
                    },
                    {
                        "@type": "SoftwareApplication",
                        "name": "Meta Tag Generator",
                        "url": "https://nineproo.com/meta",
                        "applicationCategory": "UtilitiesApplication",
                        "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" }
                    },
                    {
                        "@type": "SoftwareApplication",
                        "name": "AI Prompt Helper",
                        "url": "https://nineproo.com/prompt",
                        "applicationCategory": "UtilitiesApplication",
                        "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" }
                    }
                ]
            }
        ]
    },

    '/glass': {
        title: 'Glassmorphism Generator – Create Frosted Glass UI Effects in CSS | NineProo',
        description: 'Generate modern glassmorphism UI effects with our free CSS generator. Customize blur, transparency, borders, and shadows. Export CSS, Tailwind, or React code instantly.',
        keywords: ['glassmorphism generator', 'glassmorphism css', 'frosted glass ui', 'glass effect css'],
        canonical: 'https://nineproo.com/glass',
        ogImage: '/og-glass.png',
        schema: [
            {
                "@context": "https://schema.org",
                "@type": "SoftwareApplication",
                "name": "Glassmorphism Generator",
                "applicationCategory": "DesignApplication",
                "operatingSystem": "Any",
                "url": "https://nineproo.com/glass",
                "description": "Generate modern glassmorphism UI effects with customizable CSS properties.",
                "offers": {
                    "@type": "Offer",
                    "price": "0",
                    "priceCurrency": "USD",
                    "availability": "https://schema.org/InStock"
                },
                "aggregateRating": {
                    "@type": "AggregateRating",
                    "ratingValue": "4.8",
                    "reviewCount": "156",
                    "bestRating": "5",
                    "worstRating": "1"
                },
                "author": {
                    "@type": "Organization",
                    "name": "NineProo"
                },
                "featureList": [
                    "Blur customization",
                    "Transparency control",
                    "Border styling",
                    "Shadow effects",
                    "Export to CSS/Tailwind/React"
                ]
            },
            {
                "@context": "https://schema.org",
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {
                        "@type": "ListItem",
                        "position": 1,
                        "name": "Home",
                        "item": "https://nineproo.com"
                    },
                    {
                        "@type": "ListItem",
                        "position": 2,
                        "name": "Design Tools",
                        "item": "https://nineproo.com/#design-tools"
                    },
                    {
                        "@type": "ListItem",
                        "position": 3,
                        "name": "Glassmorphism Generator",
                        "item": "https://nineproo.com/glass"
                    }
                ]
            }
        ]
    },

    '/gradient-text': {
        title: 'CSS Gradient Text Generator – Animated Gradients | NineProo',
        description: 'Create beautiful gradient text effects with CSS. Support for linear and radial gradients, custom colors, and animation. Export clean CSS or Tailwind code.',
        keywords: ['gradient text generator', 'css text gradient', 'animated gradient text', 'text fill color'],
        canonical: 'https://nineproo.com/gradient-text',
        ogImage: '/og-gradient.png',
        schema: [
            {
                "@context": "https://schema.org",
                "@type": "SoftwareApplication",
                "name": "Gradient Text Generator",
                "applicationCategory": "DesignApplication",
                "operatingSystem": "Any",
                "url": "https://nineproo.com/gradient-text",
                "description": "Create beautiful gradient text effects with animated support.",
                "offers": {
                    "@type": "Offer",
                    "price": "0",
                    "priceCurrency": "USD",
                    "availability": "https://schema.org/InStock"
                },
                "featureList": [
                    "Linear & Radial gradients",
                    "Animation support",
                    "Custom colors",
                    "Tailwind CSS export"
                ]
            },
            {
                "@context": "https://schema.org",
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {
                        "@type": "ListItem",
                        "position": 1,
                        "name": "Home",
                        "item": "https://nineproo.com"
                    },
                    {
                        "@type": "ListItem",
                        "position": 2,
                        "name": "Design Tools",
                        "item": "https://nineproo.com/#design-tools"
                    },
                    {
                        "@type": "ListItem",
                        "position": 3,
                        "name": "Gradient Text Generator",
                        "item": "https://nineproo.com/gradient-text"
                    }
                ]
            }
        ]
    },

    '/shadow': {
        title: 'Box Shadow Generator – Smooth CSS Shadows | NineProo',
        description: 'Generate beautiful, layered box shadows for cards and UI elements. Customize layers, spread, blur, and color. Export CSS box-shadow code instantly.',
        keywords: ['box shadow generator', 'css shadow generator', 'smooth shadow', 'layered shadows'],
        canonical: 'https://nineproo.com/shadow',
        ogImage: '/og-shadow.png',
        schema: [
            {
                "@context": "https://schema.org",
                "@type": "SoftwareApplication",
                "name": "Box Shadow Generator",
                "applicationCategory": "DesignApplication",
                "operatingSystem": "Any",
                "url": "https://nineproo.com/shadow",
                "description": "Design beautiful, layered box shadows with CSS.",
                "offers": {
                    "@type": "Offer",
                    "price": "0",
                    "priceCurrency": "USD",
                    "availability": "https://schema.org/InStock"
                },
                "featureList": [
                    "Layered shadows",
                    "Custom spread & blur",
                    "Neumorphism support",
                    "Tailwind CSS export"
                ]
            },
            {
                "@context": "https://schema.org",
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {
                        "@type": "ListItem",
                        "position": 1,
                        "name": "Home",
                        "item": "https://nineproo.com"
                    },
                    {
                        "@type": "ListItem",
                        "position": 2,
                        "name": "Design Tools",
                        "item": "https://nineproo.com/#design-tools"
                    },
                    {
                        "@type": "ListItem",
                        "position": 3,
                        "name": "Box Shadow Generator",
                        "item": "https://nineproo.com/shadow"
                    }
                ]
            }
        ]
    },

    '/palette': {
        title: 'Color Palette Generator – Accessible Color Schemes | NineProo',
        description: 'Create harmonious color schemes for web projects. Generate monochromatic, analogous, and complementary palettes. Check contrast accessibility.',
        keywords: ['color palette generator', 'color scheme', 'web properties', 'accessible colors'],
        canonical: 'https://nineproo.com/palette',
        ogImage: '/og-palette.png',
        schema: [
            {
                "@context": "https://schema.org",
                "@type": "SoftwareApplication",
                "name": "Color Palette Generator",
                "applicationCategory": "DesignApplication",
                "operatingSystem": "Any",
                "url": "https://nineproo.com/palette",
                "description": "Generate harmonious color palettes for web design.",
                "offers": {
                    "@type": "Offer",
                    "price": "0",
                    "priceCurrency": "USD",
                    "availability": "https://schema.org/InStock"
                },
                "featureList": [
                    "Harmony rules",
                    "Contrast checking",
                    "Export to CSS/Tailwind",
                    "Shareable links"
                ]
            },
            {
                "@context": "https://schema.org",
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {
                        "@type": "ListItem",
                        "position": 1,
                        "name": "Home",
                        "item": "https://nineproo.com"
                    },
                    {
                        "@type": "ListItem",
                        "position": 2,
                        "name": "CSS Tools",
                        "item": "https://nineproo.com/#css-tools"
                    },
                    {
                        "@type": "ListItem",
                        "position": 3,
                        "name": "Color Palette Generator",
                        "item": "https://nineproo.com/palette"
                    }
                ]
            }
        ]
    },

    '/grid': {
        title: 'CSS Grid Generator – Visual Layout Builder | NineProo',
        description: 'Visually build complex CSS grid layouts. Customize columns, rows, and gaps without writing code. Export production-ready CSS grid code.',
        keywords: ['css grid generator', 'grid layout', 'css grid builder', 'responsive grid'],
        canonical: 'https://nineproo.com/grid',
        ogImage: '/og-grid.png',
        schema: [
            {
                "@context": "https://schema.org",
                "@type": "SoftwareApplication",
                "name": "CSS Grid Generator",
                "applicationCategory": "DesignApplication",
                "operatingSystem": "Any",
                "url": "https://nineproo.com/grid",
                "description": "Visual CSS Grid layout builder.",
                "offers": {
                    "@type": "Offer",
                    "price": "0",
                    "priceCurrency": "USD",
                    "availability": "https://schema.org/InStock"
                },
                "featureList": [
                    "Visual grid builder",
                    "Area naming",
                    "Gap control",
                    "Responsive code export"
                ]
            },
            {
                "@context": "https://schema.org",
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {
                        "@type": "ListItem",
                        "position": 1,
                        "name": "Home",
                        "item": "https://nineproo.com"
                    },
                    {
                        "@type": "ListItem",
                        "position": 2,
                        "name": "CSS Tools",
                        "item": "https://nineproo.com/#css-tools"
                    },
                    {
                        "@type": "ListItem",
                        "position": 3,
                        "name": "CSS Grid Generator",
                        "item": "https://nineproo.com/grid"
                    }
                ]
            }
        ]
    },

    '/blob': {
        title: 'Blob SVG Generator – Create Organic SVG Shapes Online | NineProo',
        description: 'Generate organic SVG blob shapes for modern web design. Customize shapes and export SVG instantly with NineProo\'s Blob SVG Generator.',
        keywords: ['blob svg generator', 'svg blob', 'organic shapes svg', 'blob maker'],
        canonical: 'https://nineproo.com/blob',
        ogImage: '/og-blob.png',
        schema: {
            "@context": "https://schema.org",
            "@type": "SoftwareApplication",
            "name": "Blob SVG Generator",
            "applicationCategory": "WebApplication",
            "operatingSystem": "Any",
            "url": "https://nineproo.com/blob",
            "description": "Generate organic SVG blob shapes for modern web design.",
            "offers": {
                "@type": "Offer",
                "price": "0",
                "priceCurrency": "USD"
            }
        }
    },

    '/contrast': {
        title: 'Contrast Checker – WCAG Accessibility Test | NineProo',
        description: 'Check color contrast ratios for WCAG AA and AAA compliance. Ensure your website colors are accessible to all users. Real-time preview.',
        keywords: ['contrast checker', 'accessibility checker', 'wcag compliance', 'color contrast'],
        canonical: 'https://nineproo.com/contrast',
        ogImage: '/og-contrast.png',
        schema: [
            {
                "@context": "https://schema.org",
                "@type": "SoftwareApplication",
                "name": "Contrast Checker",
                "applicationCategory": "UtilitiesApplication",
                "operatingSystem": "Any",
                "url": "https://nineproo.com/contrast",
                "description": "Check color contrast for WCAG accessibility compliance.",
                "offers": {
                    "@type": "Offer",
                    "price": "0",
                    "priceCurrency": "USD",
                    "availability": "https://schema.org/InStock"
                },
                "featureList": [
                    "WCAG AA/AAA check",
                    "Real-time preview",
                    "Suggestion engine",
                    "Score visualization"
                ]
            },
            {
                "@context": "https://schema.org",
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {
                        "@type": "ListItem",
                        "position": 1,
                        "name": "Home",
                        "item": "https://nineproo.com"
                    },
                    {
                        "@type": "ListItem",
                        "position": 2,
                        "name": "AI & SEO Tools",
                        "item": "https://nineproo.com/#seo-tools"
                    },
                    {
                        "@type": "ListItem",
                        "position": 3,
                        "name": "Contrast Checker",
                        "item": "https://nineproo.com/contrast"
                    }
                ]
            }
        ]
    },

    '/meta': {
        title: 'Meta Tag Generator – SEO Optimization | NineProo',
        description: 'Generate SEO-optimized meta tags, OpenGraph tags, and Twitter cards. Preview how your site appears in search results and social media.',
        keywords: ['meta tag generator', 'seo tools', 'opengraph generator', 'meta tags'],
        canonical: 'https://nineproo.com/meta',
        ogImage: '/og-meta.png',
        schema: [
            {
                "@context": "https://schema.org",
                "@type": "SoftwareApplication",
                "name": "Meta Tag Generator",
                "applicationCategory": "UtilitiesApplication",
                "operatingSystem": "Any",
                "url": "https://nineproo.com/meta",
                "description": "Generate SEO meta tags and social media previews.",
                "offers": {
                    "@type": "Offer",
                    "price": "0",
                    "priceCurrency": "USD",
                    "availability": "https://schema.org/InStock"
                },
                "featureList": [
                    "SEO meta tags",
                    "OpenGraph support",
                    "Twitter Cards",
                    "Live preview"
                ]
            },
            {
                "@context": "https://schema.org",
                "@type": "BreadcrumbList",
                "itemListElement": [
                    {
                        "@type": "ListItem",
                        "position": 1,
                        "name": "Home",
                        "item": "https://nineproo.com"
                    },
                    {
                        "@type": "ListItem",
                        "position": 2,
                        "name": "AI & SEO Tools",
                        "item": "https://nineproo.com/#seo-tools"
                    },
                    {
                        "@type": "ListItem",
                        "position": 3,
                        "name": "Meta Tag Generator",
                        "item": "https://nineproo.com/meta"
                    }
                ]
            }
        ]
    },

    '/prompt': {
        title: 'AI Prompt Helper – Generate Better AI Prompts Instantly | NineProo',
        description: 'Create clear, effective prompts for AI tools like ChatGPT and Claude. Improve output quality using NineProo\'s free AI Prompt Helper.',
        keywords: ['ai prompt generator', 'prompt engineering', 'chatgpt prompts', 'ai helper'],
        canonical: 'https://nineproo.com/prompt',
        ogImage: '/og-prompt.png',
        schema: {
            "@context": "https://schema.org",
            "@type": "SoftwareApplication",
            "name": "AI Prompt Helper",
            "applicationCategory": "WebApplication",
            "operatingSystem": "Any",
            "url": "https://nineproo.com/prompt",
            "description": "Create clear, effective prompts for AI tools like ChatGPT and Claude.",
            "offers": {
                "@type": "Offer",
                "price": "0",
                "priceCurrency": "USD"
            }
        }
    },

    // Supporting pages
    '/about': {
        title: 'About Nine Hub Tools - Free Design Tools for Developers',
        description: 'Learn about Nine Hub Tools, our mission to provide free professional design tools for web developers, and our open-source commitment.',
        keywords: ['about nine hub tools', 'web design tools', 'free developer tools'],
        canonical: 'https://nineproo.com/about',
    },

    '/contact': {
        title: 'Contact Nine Hub Tools - Get in Touch',
        description: 'Contact Nine Hub Tools for questions, feedback, or support. Reach us via email or social media.',
        keywords: ['contact nine hub tools', 'support', 'feedback'],
        canonical: 'https://nineproo.com/contact',
    },

    '/sitemap': {
        title: 'Sitemap - All NineProo Tools & Pages',
        description: 'Complete sitemap of all NineProo web design tools, company pages, and resources. Find all 9 free tools in one place.',
        keywords: ['sitemap', 'site map', 'all tools', 'navigation', 'nineproo tools'],
        canonical: 'https://nineproo.com/sitemap',
    },

    '/privacy': {
        title: 'Privacy Policy - Nine Hub Tools',
        description: 'Read our privacy policy to understand how Nine Hub Tools collects, uses, and protects your personal data.',
        keywords: ['privacy policy', 'data protection', 'privacy'],
        canonical: 'https://nineproo.com/privacy',
    },

    '/terms': {
        title: 'Terms of Service - Nine Hub Tools',
        description: 'Read our terms of service to understand your rights and responsibilities when using Nine Hub Tools.',
        keywords: ['terms of service', 'terms and conditions', 'legal'],
        canonical: 'https://nineproo.com/terms',
    },

    // New legal pages
    '/terms-of-service': {
        title: 'Terms of Service - NineProo',
        description: 'Terms of Service for NineProo. By using our free web tools, you agree to these terms. Learn about your rights, limitations, and our policies.',
        keywords: ['terms of service', 'legal', 'terms and conditions', 'user agreement'],
        canonical: 'https://nineproo.com/terms-of-service',
    },

    '/privacy-policy': {
        title: 'Privacy Policy - NineProo',
        description: 'Privacy Policy for NineProo. Learn how we collect, use, and protect your data when you use our free web design tools.',
        keywords: ['privacy policy', 'data privacy', 'cookies', 'user data'],
        canonical: 'https://nineproo.com/privacy-policy',
    },

    '/disclaimer': {
        title: 'Disclaimer - NineProo',
        description: 'Legal disclaimer for NineProo. Our web tools are provided as-is for educational purposes. Read the full disclaimer before use.',
        keywords: ['disclaimer', 'legal notice', 'liability', 'terms of use'],
        canonical: 'https://nineproo.com/disclaimer',
    },

    '/cookie-policy': {
        title: 'Cookie Policy - NineProo',
        description: 'Cookie Policy for NineProo. Learn about the cookies we use, how we use them, and how you can manage cookie preferences.',
        keywords: ['cookie policy', 'cookies', 'tracking', 'privacy'],
        canonical: 'https://nineproo.com/cookie-policy',
    },
};
