import { useState } from 'react';
import { ChevronDown } from 'lucide-react';

const faqs = [
  {
    question: 'Are these tools completely free to use?',
    answer: 'Yes! All current tools are 100% free to use with no restrictions. You can generate unlimited CSS effects, gradients, and designs. Premium features may be added in the future for advanced users, but all existing tools will remain free.'
  },
  {
    question: 'Do I need to create an account?',
    answer: 'No account required! All tools work instantly in your browser. Simply visit any tool, customize your design, and copy the generated code. No signup, no login, no hassle.'
  },
  {
    question: 'Can I use the generated code in commercial projects?',
    answer: 'Absolutely! All code generated by our tools is yours to use in any project, whether personal or commercial. No attribution required, no licensing fees.'
  },
  {
    question: 'Which browsers are supported?',
    answer: 'Our tools work on all modern browsers including Chrome, Firefox, Safari, and Edge. We recommend using the latest version of your browser for the best experience.'
  },
  {
    question: 'What code formats can I export?',
    answer: 'Most tools support multiple export formats including pure CSS, Tailwind CSS, and React/JSX. You can choose the format that best fits your workflow and copy it with one click.'
  },
  {
    question: 'How do I report a bug or request a feature?',
    answer: 'We love feedback! Contact us at hello@nineproo.com with bug reports, feature requests, or suggestions. You can also reach out via our social media channels on X or Instagram.'
  }
];

export function FAQSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <section className="py-20 bg-secondary/20">
      <div className="container mx-auto px-4">
        <div className="max-w-3xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Frequently Asked Questions
            </h2>
            <p className="text-muted-foreground">
              Everything you need to know about NineProo tools
            </p>
          </div>

          <div className="space-y-4">
            {faqs.map((faq, index) => (
              <div
                key={index}
                className="bg-card border border-border rounded-lg overflow-hidden"
              >
                <button
                  onClick={() => setOpenIndex(openIndex === index ? null : index)}
                  className="w-full px-6 py-4 text-left flex items-center justify-between hover:bg-secondary/50 transition-colors"
                  aria-expanded={openIndex === index}
                >
                  <h3 className="font-semibold pr-8">{faq.question}</h3>
                  <ChevronDown
                    className={`h-5 w-5 text-muted-foreground transition-transform flex-shrink-0 ${openIndex === index ? 'rotate-180' : ''
                      }`}
                  />
                </button>
                {openIndex === index && (
                  <div className="px-6 pb-4 text-muted-foreground">
                    {faq.answer}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
